## Import Necessary Libraries For LinearRegression Model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error 

In [2]:
# obtain the values for X and Y from the dataset of gas prices
gas_df=pd.read_csv('gas_prices.csv')
#Y variable is the year by and gas prices the X variables except australia that has nan and find how to remove it
x_variable=np.array(gas_df.iloc[:,1:])
y_variable=np.array(gas_df.Year)


## train 70% and Test 30%

In [3]:
#splitting the data into the respective test and tradin for both x and y  variables
x_train,x_test,y_train,y_test=train_test_split(x_variable,y_variable,test_size=0.30)

# # scaling the data values for x_train and test only since are the features diterming the prediction of the target
# scaler=StandardScaler()
# x_train_scaled=scaler.fit_transform(x_train)
# x_test_scaled=scaler.fit_transform(x_test)




## Init and train the the model

In [4]:
#model init using the linearRegression
model=LinearRegression()
#train the the model using the fit method or function by passing the variables x_train and y_train
model.fit(x_train,y_train)


LinearRegression()

## predict using the model

In [5]:
#make predictions on the model using the x_test data set
y_prediction=model.predict(x_test)
y_prediction

array([2002.90269715, 2002.56825909, 1993.62633906, 1994.19156454,
       2009.33418499, 2009.93870553])

## Model Accurcy And Evaluation

In [6]:
#accuracy score checks the relation between the y_test and y_prediction
# accuracy=accuracy_score(y_test,y_prediction)
# accuracy

In [7]:
x_test

array([[2.72, 2.37, 4.99, 5.24, 5.29, 3.93, 2.03, 4.51, 5.56, 1.88],
       [2.19, 1.99, 4.35, 4.59, 4.53, 3.47, 2.04, 4.11, 4.7 , 1.59],
       [1.73, 1.57, 3.41, 3.07, 3.68, 4.16, 1.56, 2.88, 2.84, 1.11],
       [1.84, 1.45, 3.59, 3.52, 3.7 , 4.36, 1.48, 2.87, 2.99, 1.11],
       [4.45, 4.08, 7.51, 7.75, 7.63, 5.74, 2.45, 5.83, 7.42, 3.27],
       [3.85, 3.59, 6.6 , 6.88, 6.73, 4.49, 2.4 , 6.21, 7.13, 2.8 ]])

In [8]:
y_test

array([2004, 2003, 1993, 1994, 2008, 2007])

In [9]:
gas_df

Year  Australia  Canada  France  Germany  Italy  Japan  Mexico  \
0   1990       1.51    1.87    3.63     2.65   4.59   3.16    1.00   
1   1991       1.96    1.92    3.45     2.90   4.50   3.46    1.30   
2   1992       1.89    1.73    3.56     3.27   4.53   3.58    1.50   
3   1993       1.73    1.57    3.41     3.07   3.68   4.16    1.56   
4   1994       1.84    1.45    3.59     3.52   3.70   4.36    1.48   
5   1995       1.95    1.53    4.26     3.96   4.00   4.43    1.11   
6   1996       2.12    1.61    4.41     3.94   4.39   3.64    1.25   
7   1997       2.05    1.62    4.00     3.53   4.07   3.26    1.47   
8   1998       1.63    1.38    3.87     3.34   3.84   2.82    1.49   
9   1999       1.72    1.52    3.85     3.42   3.87   3.27    1.79   
10  2000       1.94    1.86    3.80     3.45   3.77   3.65    2.01   
11  2001       1.71    1.72    3.51     3.40   3.57   3.27    2.20   
12  2002       1.76    1.69    3.62     3.67   3.74   3.15    2.24   
13  2003       2.19    1.99    4.35     4.59   4.53   3.47    2.04   
14  2004       2.72    2.37    4.99     5.24   5.29   3.93    2.03   
15  2005       3.23    2.89    5.46     5.66   5.74   4.28    2.22   
16  2006       3.54    3.26    5.88     6.03   6.10   4.47    2.31   
17  2007       3.85    3.59    6.60     6.88   6.73   4.49    2.40   
18  2008       4.45    4.08    7.51     7.75   7.63   5.74    2.45   

    South Korea    UK   USA  
0          2.05  2.82  1.16  
1          2.49  3.01  1.14  
2          2.65  3.06  1.13  
3          2.88  2.84  1.11  
4          2.87  2.99  1.11  
5          2.94  3.21  1.15  
6          3.18  3.34  1.23  
7          3.34  3.83  1.23  
8          3.04  4.06  1.06  
9          3.80  4.29  1.17  
10         4.18  4.58  1.51  
11         3.76  4.13  1.46  
12         3.84  4.16  1.36  
13         4.11  4.70  1.59  
14         4.51  5.56  1.88  
15         5.28  5.97  2.30  
16         5.92  6.36  2.59  
17         6.21  7.13  2.80  
18         5.83  7.42  3.27

## Calculate the MeanSquare Error in Our Model

In [10]:
#pass the y_test value and y_prediction value 
mean_squared_error_linear=mean_squared_error(y_test,y_prediction)
mean_squared_error_linear

2.0392518571242384

# Ridge Regression Model
## similar to Linear Regression only that it helps in reduction of underfitting and overfitting capabilities by use of squared values of mean.
## appropriate when there are many variables with less data set


In [11]:
from sklearn.linear_model import Ridge
#init the Ridge Regression Model by passing an alpha value greater than 0 since 0 stands for linearRegression
model_ridge_regression=Ridge(alpha=1)

### Train  The Ridge Model Using The Fit Method 

In [12]:
# use the fit method and pass the x_train, y_train
model_ridge_regression.fit(x_train,y_train)

Ridge(alpha=1)

## Predict values using the trained Ridge Model

In [13]:
#make predictions on the model using the x_test data set
y_predict_ridge=model_ridge_regression.predict(x_test)
y_predict_ridge

array([2002.8061899 , 2001.39627856, 1993.97447311, 1994.63527978,
       2007.1241617 , 2008.44384217])

In [14]:
x_test

array([[2.72, 2.37, 4.99, 5.24, 5.29, 3.93, 2.03, 4.51, 5.56, 1.88],
       [2.19, 1.99, 4.35, 4.59, 4.53, 3.47, 2.04, 4.11, 4.7 , 1.59],
       [1.73, 1.57, 3.41, 3.07, 3.68, 4.16, 1.56, 2.88, 2.84, 1.11],
       [1.84, 1.45, 3.59, 3.52, 3.7 , 4.36, 1.48, 2.87, 2.99, 1.11],
       [4.45, 4.08, 7.51, 7.75, 7.63, 5.74, 2.45, 5.83, 7.42, 3.27],
       [3.85, 3.59, 6.6 , 6.88, 6.73, 4.49, 2.4 , 6.21, 7.13, 2.8 ]])

In [15]:
y_test

array([2004, 2003, 1993, 1994, 2008, 2007])

In [16]:
gas_df

Year  Australia  Canada  France  Germany  Italy  Japan  Mexico  \
0   1990       1.51    1.87    3.63     2.65   4.59   3.16    1.00   
1   1991       1.96    1.92    3.45     2.90   4.50   3.46    1.30   
2   1992       1.89    1.73    3.56     3.27   4.53   3.58    1.50   
3   1993       1.73    1.57    3.41     3.07   3.68   4.16    1.56   
4   1994       1.84    1.45    3.59     3.52   3.70   4.36    1.48   
5   1995       1.95    1.53    4.26     3.96   4.00   4.43    1.11   
6   1996       2.12    1.61    4.41     3.94   4.39   3.64    1.25   
7   1997       2.05    1.62    4.00     3.53   4.07   3.26    1.47   
8   1998       1.63    1.38    3.87     3.34   3.84   2.82    1.49   
9   1999       1.72    1.52    3.85     3.42   3.87   3.27    1.79   
10  2000       1.94    1.86    3.80     3.45   3.77   3.65    2.01   
11  2001       1.71    1.72    3.51     3.40   3.57   3.27    2.20   
12  2002       1.76    1.69    3.62     3.67   3.74   3.15    2.24   
13  2003       2.19    1.99    4.35     4.59   4.53   3.47    2.04   
14  2004       2.72    2.37    4.99     5.24   5.29   3.93    2.03   
15  2005       3.23    2.89    5.46     5.66   5.74   4.28    2.22   
16  2006       3.54    3.26    5.88     6.03   6.10   4.47    2.31   
17  2007       3.85    3.59    6.60     6.88   6.73   4.49    2.40   
18  2008       4.45    4.08    7.51     7.75   7.63   5.74    2.45   

    South Korea    UK   USA  
0          2.05  2.82  1.16  
1          2.49  3.01  1.14  
2          2.65  3.06  1.13  
3          2.88  2.84  1.11  
4          2.87  2.99  1.11  
5          2.94  3.21  1.15  
6          3.18  3.34  1.23  
7          3.34  3.83  1.23  
8          3.04  4.06  1.06  
9          3.80  4.29  1.17  
10         4.18  4.58  1.51  
11         3.76  4.13  1.46  
12         3.84  4.16  1.36  
13         4.11  4.70  1.59  
14         4.51  5.56  1.88  
15         5.28  5.97  2.30  
16         5.92  6.36  2.59  
17         6.21  7.13  2.80  
18         5.83  7.42  3.27

## Calculate the Mean Square Error for Ridge Model
### The less it is the more efficient the model is in predciction and reliability

In [17]:
mean_square_error_ridge=mean_squared_error(y_test,y_predict_ridge)
mean_square_error_ridge

1.3670093656924351

## Lasso Regression Model
### similar to the linear regression and Ridger Regression with slight deference being that its best when the variables of are few in a dataset

In [18]:
from sklearn.linear_model import Lasso
#init the Lassdo regression model with an alpha value greater than  0  else it will behave like linear regression
lasso_reg_model=Lasso(alpha=1)

## Train the Lasso Model

In [19]:
#pass the x_train and y_train into the model using the fit method
lasso_reg_model.fit(x_train,y_train)

Lasso(alpha=1)

## Predict using the Lasso Model

In [20]:
#pass the x_test data into the model obtain the output
y_predict_lasso=lasso_reg_model.predict(x_test)
y_predict_lasso

array([2001.22019274, 1999.72375563, 1995.31342841, 1995.31781951,
       2005.92005392, 2007.07184496])

In [21]:
x_test

array([[2.72, 2.37, 4.99, 5.24, 5.29, 3.93, 2.03, 4.51, 5.56, 1.88],
       [2.19, 1.99, 4.35, 4.59, 4.53, 3.47, 2.04, 4.11, 4.7 , 1.59],
       [1.73, 1.57, 3.41, 3.07, 3.68, 4.16, 1.56, 2.88, 2.84, 1.11],
       [1.84, 1.45, 3.59, 3.52, 3.7 , 4.36, 1.48, 2.87, 2.99, 1.11],
       [4.45, 4.08, 7.51, 7.75, 7.63, 5.74, 2.45, 5.83, 7.42, 3.27],
       [3.85, 3.59, 6.6 , 6.88, 6.73, 4.49, 2.4 , 6.21, 7.13, 2.8 ]])

In [22]:
y_test

array([2004, 2003, 1993, 1994, 2008, 2007])

In [23]:
gas_df

Year  Australia  Canada  France  Germany  Italy  Japan  Mexico  \
0   1990       1.51    1.87    3.63     2.65   4.59   3.16    1.00   
1   1991       1.96    1.92    3.45     2.90   4.50   3.46    1.30   
2   1992       1.89    1.73    3.56     3.27   4.53   3.58    1.50   
3   1993       1.73    1.57    3.41     3.07   3.68   4.16    1.56   
4   1994       1.84    1.45    3.59     3.52   3.70   4.36    1.48   
5   1995       1.95    1.53    4.26     3.96   4.00   4.43    1.11   
6   1996       2.12    1.61    4.41     3.94   4.39   3.64    1.25   
7   1997       2.05    1.62    4.00     3.53   4.07   3.26    1.47   
8   1998       1.63    1.38    3.87     3.34   3.84   2.82    1.49   
9   1999       1.72    1.52    3.85     3.42   3.87   3.27    1.79   
10  2000       1.94    1.86    3.80     3.45   3.77   3.65    2.01   
11  2001       1.71    1.72    3.51     3.40   3.57   3.27    2.20   
12  2002       1.76    1.69    3.62     3.67   3.74   3.15    2.24   
13  2003       2.19    1.99    4.35     4.59   4.53   3.47    2.04   
14  2004       2.72    2.37    4.99     5.24   5.29   3.93    2.03   
15  2005       3.23    2.89    5.46     5.66   5.74   4.28    2.22   
16  2006       3.54    3.26    5.88     6.03   6.10   4.47    2.31   
17  2007       3.85    3.59    6.60     6.88   6.73   4.49    2.40   
18  2008       4.45    4.08    7.51     7.75   7.63   5.74    2.45   

    South Korea    UK   USA  
0          2.05  2.82  1.16  
1          2.49  3.01  1.14  
2          2.65  3.06  1.13  
3          2.88  2.84  1.11  
4          2.87  2.99  1.11  
5          2.94  3.21  1.15  
6          3.18  3.34  1.23  
7          3.34  3.83  1.23  
8          3.04  4.06  1.06  
9          3.80  4.29  1.17  
10         4.18  4.58  1.51  
11         3.76  4.13  1.46  
12         3.84  4.16  1.36  
13         4.11  4.70  1.59  
14         4.51  5.56  1.88  
15         5.28  5.97  2.30  
16         5.92  6.36  2.59  
17         6.21  7.13  2.80  
18         5.83  7.42  3.27

## Calculation of The Mean Squared Error of The Lasso Model Regression
### The lesser the error the better

In [24]:
mean_squared_error_lasso=mean_squared_error(y_test,y_predict_lasso)
mean_squared_error_lasso

4.980173711380595

## General Results of the Models: Linear, Ridge and Lasso Regression Model

In [25]:
print("Linear Model Mean Squared Error:", mean_squared_error_linear)
print()
print("Ridge Model Mean Squared Error:", mean_square_error_ridge)
print()
print("Lasso Model Mean Squared Error:", mean_squared_error_lasso)
print()


Linear Model Mean Squared Error: 2.0392518571242384

Ridge Model Mean Squared Error: 1.3670093656924351

Lasso Model Mean Squared Error: 4.980173711380595



## The Best Predicted Model and Worst Predicted Model

In [26]:
all_errors=np.asarray([mean_squared_error_linear, mean_square_error_ridge,mean_squared_error_lasso])

print("Best Model is:", all_errors.min())
print()

Best Model is: 1.3670093656924351

